### ISSUE TITLE
is Client up to date with current auth0 API?

### ISSUE THREAD

**Issue by isc-rsingh** [thameera/auth0-react-python-api-sample#2]
For the life of me I couldn't get this client to generate the proper access token until I read through https://community.auth0.com/t/access-token-too-short-jwt-malformed/9169/5 and changed my code from using the `Auth0Lock` class to `auth0.WebAuth`. I notice this code is about a year old so I'm wondering if the Auth0Lock class works anymore.

**Comment by thameera** [comment]
Things have changed a lot since last year, so I'd recommend that you start with the latest versions of these two repos separately:

* https://github.com/auth0-samples/auth0-react-samples/
* https://github.com/auth0-samples/auth0-python-api-samples/

I haven't updated this repo and don't plan to, so will put a deprecated notice.
